"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main/version_cv2_speed/imageLayering.py']
DATA_FILES = []
OPTIONS = {
    'iconfile':'image/icon.icns'
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app','opencv-python','blend_modes','pillow'],
)
